### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by HiImJulien** [joeyates/rake-builder#26]
Hi, 
I am currently thinking about using Rake for a small C project.
However, rake is failing to build and run the given "hello-world"-example.
With the error:
`Das System kann den angegebenen Pfad nicht finden.`

Which means:
`The system cannot find the given path.`

Is rake-builder supposed to work on Windows too or only restricted to UNIX system?

Sincerely,
Julien

**Comment by joeyates** [comment]
Hello Julien,

I've never used rake-builder on Windows.

I'll need to understand what path is not being found.
 
I've added a problem resolution section to the [README](https://github.com/joeyates/rake-builder#problem-resolution). Could you run `rake --trace` and post the output here?

Just to check: do you have `gcc` installed? Currently, this project only works with that compiler.

**Comment by HiImJulien** [comment]
This is what I have got so far:
```
** Invoke build (first_time)
** Invoke compile (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke ./.main_c.depend.mf (first_time)
** Invoke load_local_config (first_time)
** Invoke .rake-builder (first_time, not_needed)
** Execute load_local_config
** Invoke missing_headers (first_time)
** Execute missing_headers
Das System kann den angegebenen Pfad nicht finden.
Das System kann den angegebenen Pfad nicht finden.
** Invoke . (first_time, not_needed)
** Invoke ./main.c (first_time, not_needed)
** Execute ./.main_c.depend.mf
Das System kann den angegebenen Pfad nicht finden.
rake aborted!
makedepend not found
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-builder-0.9.2/lib/rake/builder.rb:258:in `create_makedepend_file'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-builder-0.9.2/lib/rake/builder/task_definers/builder_task_definer.rb:101:in `block in define'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:240:in `call'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:235:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rake-builder-0.9.2/lib/rake/microsecond_task.rb:37:in `execute'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:106:in `each'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby22-x64/lib/ruby/2.2.0/rake/application.rb:75:in `run'
C:/Ruby22-x64/bin/rake:33:in `<main>'
Tasks: TOP => build => compile => ./.main_c.depend.mf
```

But this is without having GCC/MinGW installed. Tried it with MSVC and Clang.

EDIT: I have just installed the MinGW Suite and added it to the path. Doesn't work neither. Complains with the same error.

**Comment by joeyates** [comment]
OK, so the relevant line seems to be
```
makedepend not found
```

I've found this port: http://llg.cubic.org/docs/vc7.html

**Comment by HiImJulien** [comment]
Are there any plans for the future to create a standalone version of 'rake-builder', which works out of the box on Windows? (I'd like to do that, but my expearence with Ruby has been only a 'HelloWorld'-script and a dead simple rails app.)

**Comment by joeyates** [comment]
I hadn't planned anythng standalone, no.

**Comment by joeyates** [comment]
Have you installed makedepend?
